### ISSUE TITLE
OOM with 3090 (24GB) (Not surpriced)

### ISSUE THREAD

**Issue by Kallamamran** [junhahyung/STGuidance#4]
What is the requirements to run this. I'm running with --cpu_offload and OOM's directly. Is 40GB VRAM a minumum

```
Launching with 1 GPUs. If you want to force single GPU mode use CUDA_VISIBLE_DEVICES=0.
Attention mode: sdpa
Timing load_text_encoder
Timing load_dit
Timing load_vae
Stage                   Time(s)    Percent
load_text_encoder          0.72      2.01%
load_dit                  30.49     85.15%
load_vae                   4.59     12.83%
Max memory reserved: 0.00 GB
moving model from cpu -> cuda:0
moving model from cuda:0 -> cpu
Max memory reserved: 17.85 GB
moving model from cpu -> cuda:0
Traceback (most recent call last):
  File "Q:\Mochi-STG\venv\lib\site-packages\gradio\queueing.py", line 624, in process_events
    response = await route_utils.call_process_api(
  File "Q:\Mochi-STG\venv\lib\site-packages\gradio\route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
  File "Q:\Mochi-STG\venv\lib\site-packages\gradio\blocks.py", line 2019, in process_api
    result = await self.call_function(
  File "Q:\Mochi-STG\venv\lib\site-packages\gradio\blocks.py", line 1566, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "Q:\Mochi-STG\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "Q:\Mochi-STG\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "Q:\Mochi-STG\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "Q:\Mochi-STG\venv\lib\site-packages\gradio\utils.py", line 865, in wrapper
    response = f(*args, **kwargs)
  File "Q:\Mochi-STG\demos\cli.py", line 103, in generate_video
    final_frames = pipeline(**args)
  File "Q:\Mochi-STG\src\genmo\mochi_preview\pipelines.py", line 560, in __call__
    with move_to_device(self.dit, self.device):
  File "C:\Program Files\Python310\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "Q:\Mochi-STG\src\genmo\mochi_preview\pipelines.py", line 499, in move_to_device
    model.to(target_device)
  File "Q:\Mochi-STG\venv\lib\site-packages\torch\nn\modules\module.py", line 1340, in to
    return self._apply(convert)
  File "Q:\Mochi-STG\venv\lib\site-packages\torch\nn\modules\module.py", line 900, in _apply
    module._apply(fn)
  File "Q:\Mochi-STG\venv\lib\site-packages\torch\nn\modules\module.py", line 900, in _apply
    module._apply(fn)
  File "Q:\Mochi-STG\venv\lib\site-packages\torch\nn\modules\module.py", line 900, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "Q:\Mochi-STG\venv\lib\site-packages\torch\nn\modules\module.py", line 927, in _apply
    param_applied = fn(param)
  File "Q:\Mochi-STG\venv\lib\site-packages\torch\nn\modules\module.py", line 1326, in convert
    return t.to(
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 192.00 MiB. GPU 0 has a total capacity of 24.00 GiB of which 0 bytes is free. Of the allocated memory 21.62 GiB is allocated by PyTorch, and 1.56 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

**Comment by kinam0252** [comment]
Hi, thank you for your interest and question!😊 Since the implementation is based on mochi's base code, you can refer to the [mochi GitHub](https://github.com/genmoai/mochi) repository for the requirements. 

During our testing, we used four A100 GPUs with 80GB of VRAM each. By reducing the resolution or the number of frames, less VRAM might be feasible, but it still seems like significantly more than 40GB VRAM would be necessary.

By the way, we are planning to work on making mochi run with lower VRAM requirements, so please look forward to further updates!

**Comment by kinam0252** [comment]
We’ve implemented STG in the Mochi diffusers pipeline and updated it at **[MochiSTGPipeline](https://github.com/junhahyung/STGuidance/tree/main/diffusers/mochi)**. 

By removing `pipe = pipe.to("cuda")` and enabling:

```python
pipe.enable_model_cpu_offload()
pipe.enable_vae_tiling()
```
you can run it with less memory. While we can’t guarantee it will avoid OOM issues on an RTX 3090, reducing height, width, and num_frames can also help lower memory usage. It’s worth a try—would you like to check it out?
